// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

type Item struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Price int32  `json:"price"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Age  int32  `json:"age"`
}
