// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, db DBTX, name string, age int32) (User, error)
	GetItems(ctx context.Context, db DBTX) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
