// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package easyjsonsample

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson89aae3efDecodeGithubComEhsundarEhsandarcomContentPostsGoCodeGenApproachesCodesEasyjsonsample(in *jlexer.Lexer, out *sampleStructure) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "age":
			out.Age = int(in.Int())
		case "height":
			out.Height = float32(in.Float32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson89aae3efEncodeGithubComEhsundarEhsandarcomContentPostsGoCodeGenApproachesCodesEasyjsonsample(out *jwriter.Writer, in sampleStructure) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"age\":"
		out.RawString(prefix)
		out.Int(int(in.Age))
	}
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Float32(float32(in.Height))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v sampleStructure) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson89aae3efEncodeGithubComEhsundarEhsandarcomContentPostsGoCodeGenApproachesCodesEasyjsonsample(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v sampleStructure) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson89aae3efEncodeGithubComEhsundarEhsandarcomContentPostsGoCodeGenApproachesCodesEasyjsonsample(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *sampleStructure) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson89aae3efDecodeGithubComEhsundarEhsandarcomContentPostsGoCodeGenApproachesCodesEasyjsonsample(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *sampleStructure) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson89aae3efDecodeGithubComEhsundarEhsandarcomContentPostsGoCodeGenApproachesCodesEasyjsonsample(l, v)
}
